### PR TITLE
Port add-on to WebExtensions API (without actually using any of it)

### LINKED ISSUE #1: Does not work with <a name=""> anchors
The addon does not support classic `<a name="">` anchors at all.

To my knowledge, instead of nesting stuff inside the `<a>` element, real world pages mostly use these by including an anchor _inside the heading element_ like this:

```
<h1>This is a nice heading<a name="nice_heading"></a></h1>
```

An example of this technique can be seen [here](http://www.mojohaus.org//build-helper-maven-plugin/usage.html).

### LINKED ISSUE #2: Port to WebExtensions API
Please consider porting this awesome add-on to [WebExtension API](https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Getting_Started_with_Firefox_Extensions), the only add-on API supported in Firefox 57+ (and Chrome etc.).

### PR DESCRIPTION
**Pull request by kernc**
Closes https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/issues/2, fixes https://github.com/certainlyakey/Copy-current-page-URL-with-anchor/issues/1.

Before merging this, you may wish to do `git tag 0.21` on master branch, followed by `git push --tags`. This way a quick reference to the SDK version is retained.

I made this 1.0 and I allowed myself to reword a little. Nothing of WebExtensions API is used as that is pretty much ill-designed and useless.

Be happy to write tests for it, but I've no idea how.

Please review.

### CODE REVIEW

**Comment by kernc** [comment]
I'd also like to support the following syntax:
```html
<a name=...>
<h2>...</h2>
```
Such as in https://cacm.acm.org/magazines/2016/7/204032-why-google-stores-billions-of-lines-of-code-in-a-single-repository/fulltext

Stay put.

**Comment by kernc** [comment]
Updated. Seems to work!

**Review by certainlyakey — APPROVED** [review]
Seems like everything's cool! Thanks for the PR, the updated extension is submitted to AMO.

**Comment by kernc** [comment]
Well that was fast, thanks!

The reason I couldn't do with WebExtensions menus is that they are async and only allowed to be configured in a background script. But then the content script must somehow let the background script know of the clicked element via a message, because the menu needs to be updated with the clicked anchor's label, or the menu item hidden completely if there is now anchor. But the content script can't do that in an async manner in time before the menu is shown. Therefore I used [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#Browser_compatibility), and due to this, the extension currently doesn't work in Chromium. But it should eventually.

**Comment by certainlyakey** [comment]
Same's true for you! :) Thanks for the work done. I do not care about Chromium.

**Comment by yzhang-gh** [comment]
This extension is awesome.

Would you like to also submit it to the Chrome Web Store? I use both Firefox and Chrome. It would be great to have this in both of them.

**Comment by kernc** [comment]
@yzhang-gh Have you tried, does the extension as-is work in Chrome?

**Comment by yzhang-gh** [comment]
I will have a try when I get back home tonight.

**Comment by yzhang-gh** [comment]
I tried, but no such luck 😔.

So I made a Chrome version by Googling a lot...

Followed is the code if anyone is interested.

<details>
<summary><code>manifest.json</code></summary>

```json
{
    "name": "Copy with Anchor",
    "description": "Copy a link with the anchor",
    "version": "0.1",
    "permissions": [
        "contextMenus"
    ],
    "background": {
        "scripts": [
            "background.js"
        ],
        "persistent": false
    },
    "content_scripts": [
        {
            "matches": [
                "<all_urls>"
            ],
            "js": [
                "content.js"
            ]
        }
    ],
    "manifest_version": 2
}
```

</details>

<details>
<summary><code>content.js</code></summary>

```js
document.addEventListener("mousedown", function (event) {
    if (event.button !== 2) {
        return;
    }

    var target = event.target;
    while (!target.id) {
        if (target.previousElementSibling !== null) {
            target = target.previousElementSibling;
        } else {
            target = target.parentElement;
            if (target === null) {
                return;
            }
        }
    }

    chrome.runtime.sendMessage({
        'message': 'updateContextMenu',
        'anchor': target.id
    });
}, true);

chrome.runtime.onMessage.addListener(function (request) {
    if (request.message == 'copyAnchor') {
        var input = document.createElement('input');
        input.display = 'none';
        input.value = window.location.href.split('#')[0] + '#' + request.anchor;
        document.body.appendChild(input);
        input.select();
        document.execCommand('copy');
        document.body.removeChild(input);
    }
});
```

</details>

<details>
<summary><code>background.js</code></summary>

```js
// Add a message listener that will modify the context menu item
chrome.runtime.onMessage.addListener(function (request) {
    if (request.message == 'updateContextMenu') {
        chrome.contextMenus.update(
            'copy-anchor-menu-item',
            {
                'title': 'Copy anchor link #' + request.anchor.substr(0, 20) + (request.anchor.length > 20 ? '…' : ''),
                "contexts": ["page", "link", "image"]
            },
            function () {
                chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
                    chrome.tabs.sendMessage(tabs[0].id, {
                        'message': 'copyAnchor',
                        'anchor': request.anchor
                    });
                });
            }
        );
    }
});

// The context menu item.
chrome.contextMenus.create({
    'id': 'copy-anchor-menu-item',
    'title': 'Copy anchor link',
    "contexts": ["page", "link", "image"]
});
```

</details>

**Pull request merged**
